version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  cry-me-a-river.cyrhades.fr:
    image: anssi/fcsc2023-crypto-cry-me-a-river:latest
    read_only: true
    ports:
      - ${PORT_SSH}:4000
